### ISSUE TITLE
Not parsing inside methods?

### ISSUE THREAD

**Issue by djMax** [daliwali/docchi#4]
I have the following:

````
/**
 * Container for addresses used on various invoice entities
 * @class
 */
Invoice.Address = class {
    constructor() {
        /**
         * @memberOf Invoice.Address
         * @member {string} line2
         */
    }
};
````

docchi parses the first comment but not the second. Any idea why?

**Comment by daliwali** [comment]
Right now it only looks *ahead* of a comment for an expression to match, and not before.

**Comment by daliwali** [comment]
I just pushed `0.5.1`, so unmatched comments should be included in the output.

**Comment by djMax** [comment]
I see it getting parsed now. Unfortunately there's no context for it - any way to pull in the scoping type or method or something?

**Comment by djMax** [comment]
Also this seems like it should've gotten a context but didn't:

````
/**
 * Valid invoice statuses
 * @enum {string}
 */
Invoice.Status = {
    /**
     * The invoice has not been saved to the server
     */
    NEW: "NEW",
};
````
It picks up the Invoice.Status comment fine, but the value comment is not properly located (IMHO)

**Comment by daliwali** [comment]
You are correct, there are quite a few AST nodes it doesn't match yet, I will try to cover a lot more use cases. As of `0.5.2`, comments expose a `location` property, and if you really want to you can try to match comments to the AST yourself. The instance has `this.comments` and `this.AST` which it uses internally to match comments to their context. 

Matching an object property in this way shouldn't be too difficult though, will look into it.

**Comment by daliwali** [comment]
I just pushed `0.5.3` which should resolve your use case, there are [tests](https://github.com/daliwali/docchi/blob/master/test/fixtures/fixture2.js#L28) for it as well.

**Comment by djMax** [comment]
Thanks, this is fantastic. I love your comment on the README that basically this module shouldn't exist. But until JSDoc handles ES6 properly, I'm all about docchi. :) FYI, we're using it to try taking JS and code-gening interfaces in java/objc/.net

**Comment by djMax** [comment]
So in that example/test, the context for "value" is Person. Shouldn't it be Person.thing?

**Comment by djMax** [comment]
Looking at the parser and code and such I can see that this might either be "very hard" or actually ambiguous. I think I can work around it by keying off the enum tag and then just evaling the damn fragment and pulling them out. Or maybe by just doing some comment range matching...

**Comment by daliwali** [comment]
Yeah, I was thinking that matching backwards would be ambiguous, so it wasn't something I wanted to touch. 

You're right, the target is incorrect, fixed the behavior and tests as you described and pushed as `0.6.0`.
