### ISSUE TITLE
Empty array as output

### ISSUE THREAD

**Issue by balupton** [daliwali/docchi#5]
```
$ git clone https://github.com/bevry/taskgroup.git taskgroup
$ cd taskgroup
$ git checkout es6
$ npm i docchi
docchi@0.5.0 node_modules/docchi
├── acorn@1.0.1
├── doctrine@0.6.4 (isarray@0.0.1, esutils@1.1.6)
├── babel-runtime@4.7.16 (core-js@0.6.1)
└── commonmark@0.18.1
$ ./node_modules/.bin/docchi < es6/lib/taskgroup.js
[]
```

File in question: https://github.com/bevry/taskgroup/blob/ce68612288191444c4d01ea31abbacea0c295fb8/es6/lib/taskgroup.js

**Comment by daliwali** [comment]
This is because the default parser is JSDoc. In order to parse this, you will need to pass in a custom function to the [`output` method](https://github.com/daliwali/docchi/blob/master/lib/index.js#L42).

**Comment by balupton** [comment]
@daliwali cool, those comments is tomdoc style. I was hoping that dochi would be able to generate most of the docs from the code itself, then use tomdoc or jsdoc to add more information.

Re 0.5.2, still getting the same empty array issue.

**Comment by daliwali** [comment]
Perhaps you didn't change the default parser? Right now the CLI is pretty dumb and doesnt do anything other than stdio, so you have to use docchi programmatically:

```js
import fs from 'fs';
import Docchi from './lib';

let doc = new Docchi(fs.readFileSync('taskgroup.js'));
let output = doc.output((comment, options) => {
  return comment;
});

console.log(output);
```

I hope that resolves your issue. I should look into parsing CLI options though.
